#version: '3.8'
#services:
#   web:
#       build: .
#       command: python manage.py runserver localhost:8000
#       ports:
#           - 8000:8000
version: "3.8"
services:
  ddda:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"