# Generated by Django 3.2.8 on 2021-11-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_operator', models.CharField(max_length=20, null=True, verbose_name='Туроператор')),
                ('airline', models.CharField(max_length=30, null=True, verbose_name='Авиакомпания')),
                ('flight_number', models.CharField(max_length=6, verbose_name='Номер рейса')),
                ('arrival_city', models.CharField(max_length=20, verbose_name='Город отправки')),
                ('departure_city', models.CharField(max_length=20, verbose_name='Город назначения')),
                ('departure_country', models.CharField(max_length=20, verbose_name='Страна назначения')),
                ('hotel_name', models.CharField(max_length=30, verbose_name='Название отеля')),
                ('room_type', models.CharField(choices=[('standard', 'Стандартный'), ('apartment', 'Апартаменты'), ('double', 'Двуместный'), ('single', 'Одноместный'), ('triple', 'Трехместный'), ('business', 'Бизнес'), ('family', 'Семейный')], max_length=10, null=True, verbose_name='Тип комнаты')),
                ('meals_type', models.CharField(choices=[('AI', 'Все включено'), ('BB', 'Завтраки'), ('HB', 'Полупансион'), ('OB', 'Без еды'), ('FB', 'Полный пансион')], max_length=2, null=True, verbose_name='Тип питания')),
                ('transfer', models.BooleanField(default=False, verbose_name='Наличие трансфера')),
                ('insurance', models.BooleanField(default=False, verbose_name='Наличие страховки')),
            ],
        ),
    ]
