# Generated by Django 3.2.8 on 2021-11-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_travel', models.DateField(verbose_name='Дата поездки')),
                ('number_of_tourists', models.IntegerField(verbose_name='Количество туристов')),
                ('state', models.CharField(choices=[('b', 'booked'), ('p', 'paid'), ('conf', 'confirmed'), ('d', 'deposit'), ('t', 'trip'), ('can', 'cancelled'), ('comp', 'completed')], max_length=10, verbose_name='Статус')),
                ('number_rest_days', models.IntegerField(verbose_name='Количество дней отпуска')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package', verbose_name='Туристичесуий пакет')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Клиент')),
            ],
        ),
    ]
