# Generated by Django 3.2.8 on 2021-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211103_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('booked', 'Забронирован'), ('paid', 'Оплачен'), ('confirmed', 'Подтвержден'), ('deposit', 'Депосит'), ('trip', 'Отдыхает'), ('cancelled', 'Отменен'), ('completed', 'Завершен')], max_length=10, verbose_name='Статус'),
        ),
    ]
