version: "3.8"
services:
  postgres:
    container_name: postgres_ninel
    image: postgres
    environment:
      POSTGRES_USER: ninel
      POSTGRES_PASSWORD: gnb17062001
      POSTGRES_DB: ninel_db
      PGDATA: /data/postgres
    volumes:
      - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped

  ddda:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - 1221:80
    volumes:
      - /app/staticfiles/
    depends_on:
      - ddda
