# Generated by Django 3.2.8 on 2021-11-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Туристический пакет', 'verbose_name_plural': 'Туристические пакеты'},
        ),
    ]
