# Generated by Django 4.0 on 2021-12-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Забавное слово')),
            ],
            options={
                'verbose_name': 'Забавное слово',
                'verbose_name_plural': 'Забавные слова',
            },
        ),
    ]
