# Generated by Django 3.2.8 on 2021-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('w', 'Женщина')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='Номер паспорта'),
        ),
    ]
