# Generated by Django 3.2.8 on 2021-11-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('m', 'man'), ('w', 'women')], max_length=1, verbose_name='Пол')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Телефонный номер')),
            ],
        ),
    ]
